FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:2.4.0-gpu-py311-cu124-ubuntu22.04-ec2

RUN mkdir -p /workspace/

WORKDIR /workspace

RUN echo "Using llama patch ..."
RUN git clone https://github.com/meta-llama/llama-cookbook && \
    cd llama-cookbook && \
    git checkout a346e19df9dd1a9cddde416167732a3edd899d09 && \
    curl -L -o patch-llama-cookbook.tar.gz https://raw.githubusercontent.com/aws/deep-learning-containers/master/examples/dlc-llama-3-finetuning-and-hosting-with-agent/patch-llama-cookbook.tar.gz && \
    tar -xzf patch-llama-cookbook.tar.gz && \
    cd patch-llama-cookbook && \
    git config --global user.email "you@example.com" && \
    git am *.patch

WORKDIR /workspace/llama-cookbook

RUN pip3 install -U pip setuptools

RUN pip3 install huggingface_hub[cli]
RUN pip3 install -r requirements.txt

RUN pip3 install -e .

RUN pip3 install tabulate

RUN pip3 install protobuf

RUN pip3 install python-etcd

ENV PYTHONPATH="${PYTHONPATH}:/workspace/llama-recipes/src"
