#!/bin/bash
# pushd ../../..
# CLUSTER_NAME=$(./eks-name.sh)
# popd
# CONFIG - configuration type for EKS, CONFIG=conf(default)|yaml
# Set CONFIG=yaml and edit eks.yaml to use advanced cluster configuration options
# like efaEnabled.
# When a yaml file is used to configure the cluster, please set CLUSTER_NAME in this file to match
# the cluster name specified in the yaml.
# Refer to yaml file schema here: https://eksctl.io/usage/schema/
# or examples here: https://github.com/weaveworks/eksctl/tree/main/examples
export CONFIG=yaml
if [ -f ${HOME}/.aws/credentials ]; then
        # Only set AWS_PROFILE when AWS CLI credentials are configured
        export AWS_PROFILE=default
fi
# EKS_YAML - path to cluster yaml manifest to use in case CONFIG=yaml
export EKS_YAML=/home/ubuntu/blog/eks.conf
# EKS Cluster
export CLUSTER_NAME=eks-blog-dev
export CLUSTER_REGION=us-west-2
export CLUSTER_ZONES=us-west-2a

# FSX Configuration
# All settings are required

## IAM Policy to provide access to FSx, if configured policy name does not exist, it will be created.
export FSX_POLICY_NAME=fsx-s3-csi
export FSX_POLICY_DOC=file://fsx-policy.json

## Derive
asg1_name=$(eksctl get nodegroups --cluster $CLUSTER_NAME | grep -v NAME | head -n 1 | awk '{print $10}')
launch_template_name=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name=$asg1_name | jq -r '.AutoScalingGroups[].MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateName')
instance_profile_name=$(aws ec2 describe-launch-template-versions --versions '$Default' --launch-template-name=$launch_template_name | jq -r '.LaunchTemplateVersions[].LaunchTemplateData.IamInstanceProfile.Name')
instance1_id=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name=$asg1_name | jq -r '.AutoScalingGroups[].Instances[0].InstanceId')
subnet_id=$(aws ec2 describe-instances --instance-id=$instance1_id | jq -r '.Reservations[0].Instances[0].SubnetId')
## Instance profiles of EKS node groups that will have access to FSx. Space separated string enclosed in ().
export EKS_INSTANCE_PROFILE_NAMES=($instance_profile_name)

## Subnet to use for all EKS nodes and FSx volumes

export FSX_SUBNET_ID=$subnet_id

## Security group name for access to FSx volumes. Will be created if it does not exist.
export FSX_SECURITY_GROUP_NAME=$(aws eks describe-cluster --name eks-blog-dev --region us-west-2 --query 'cluster.resourcesVpcConfig.clusterSecurityGroupId'   --output text |   xargs aws ec2 describe-security-groups --region us-west-2 --group-ids   --query 'SecurityGroups[0].GroupName')
## Name of FSX storage class to create or update
export FSX_STORAGE_CLASS_NAME=fsx-sc

